#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Image-Orientation
version:      0.01
version_from: Orientation.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
